name: AWS Lambda Zip Deploy - Python
author: Gautham
description: Deploy code to AWS Lambda.
inputs:
  lambda_function_name:
    description: The Lambda function name. Check the AWS docs/readme for examples.
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.lambda_function_name }}
    - ${{ inputs.lambda_region }}
